# Generated by Django 4.2.7 on 2023-11-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=100)),
                ('medico_nome', models.CharField(max_length=100)),
                ('medicamentos', models.TextField()),
                ('data_prescricao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
